# Generated by Django 3.0 on 2022-06-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoursCalc', '0010_shift_break_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='duration',
        ),
    ]
