# Generated by Django 3.0 on 2022-06-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190110_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
